// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tosrjpdztyamtfmntkob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvc3JqcGR6dHlhbXRmbW50a29iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NzA4NjUsImV4cCI6MjA2OTM0Njg2NX0.SQGiE6o5-bMnMemeEXkD2f17xyUx33rNILpkO7tmUfc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});